baseURL: https://berlingoqc.github.io/course-introduction-fullstack
languageCode: en-us
title: Course Introduction to Programmation for FullStack development
defaultContentLanguageInSubdir: true

theme: "hugo-theme-learn"

params:
  themeVariant: "berlingoqc"
  disableLandingPageButton: true


outputs:
  home: [ "HTML", "RSS", "JSON"]
